name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set Google Cloud project
      - name: Set Google Cloud project
        run: |
          echo "PROJECT_ID=terrasync-441508" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --impersonate-service-account=458189808803-compute@developer.gserviceaccount.com \
            --tag gcr.io/$PROJECT_ID/terrasync-server:latest \
            ./Server

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy terrasync-server \
            --impersonate-service-account=458189808803-compute@developer.gserviceaccount.com \
            --image gcr.io/$PROJECT_ID/terrasync-server:latest \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated
