name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          impersonate_service_account: 458189808803-compute@developer.gserviceaccount.com

      # Set Google Cloud project
      - name: Set Google Cloud project
        run: |
          echo "PROJECT_ID=terrasync-441508" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag gcr.io/$PROJECT_ID/terrasync-server:latest \
            ./Server

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: terrasync-server
          region: asia-southeast2
          image: gcr.io/${{ env.PROJECT_ID }}/terrasync-server:latest
